server:
  port: 9000
  servlet:
    session:
      timeout: 90m

#mysql_setting
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      # Redis 연결 타임아웃 설정 추가
      connect-timeout: 3000
      timeout: 3000
      # Lettuce 클라이언트 설정
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 1000
logging:
  level:
    "[root]": INFO # [전체 로깅 레벨]
    "[boot.infopass]": DEBUG # [프로젝트 패키지 로깅 레벨]
    "[org.springframework.data.redis]": DEBUG # [Redis 로깅 레벨]
    "[io.lettuce]": DEBUG # [Lettuce 로깅 레벨]
    "[org.springframework.cache]": DEBUG # [캐시 로깅 레벨]

#mybatis
mybatis:
  type-aliases-package: boot.infopass.dto
  mapper-locations:
    - /mapper/*.xml

jwt:
  secret-key: ${JWT_SECRET}

social:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}
